### PR TITLE
Added detection for non-resources xml file to prevent errors

### PR DESCRIPTION
**Pull request by mariotaku**
Hi, it's me again 😸 , thanks for this awesome plugin!

This PR adds detection for non-resources xml file, and hides menu entry for them.

For AndroidManifest.xml and so on:
image

For strings.xml, arrays.xml and so on:
image

### CODE REVIEW

**Comment by roana0229** [comment]
Hi, thank you as always! 😄 
I will confirm soon.

**Comment by roana0229** [comment]
I Compiled this branch. And not found `XMLInputFactory.newFactory()` method. 😢 
I found `XMLInputFactory.newInstance()`.
But, `XMLInputFactory.newInstance()` is deprecated.

I am using environment this.

```
IntelliJ IDEA 2016.3.5
Build #IC-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

@mariotaku  Please teach your environment and setting.  🙏

**Comment by mariotaku** [comment]
Sorry, maybe it's an incompatible method. I'll check tomorrow. How to print out our development environment by the way?

**Comment by roana0229** [comment]
> I'll check tomorrow

Thank you 😃 

I copied this way.
IntelliJ IDEA Menu > About IntelliJ IDEA > Copy to Clipboard (show when hover mouse on environment)

**Comment by mariotaku** [comment]
My environment seems identical
````
IntelliJ IDEA 2016.3.5
Build #IC-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
````

...While project SDK is
`Android Studio AI-143.2821654`

**Comment by mariotaku** [comment]
@roana0229 Done! I guess this problem was fixed, to make sure this works we could run it and try.

**Comment by roana0229** [comment]
👀 I will confirm tonight.

**Comment by roana0229** [comment]
Awesome 👍

**Pull request merged**
